### ISSUE TITLE
optimisations needed

### ISSUE THREAD

**Issue by tigercoding56** [pygame-web/pygbag#105]
i know wasm is less performant than desktop , but    this is almost a 40 times reduction of framerate ? maybe there ought to be optimisation work
also there seem to be small periods when the browser is able to get high framerates ? 
(i am using firefox on manjaro , and the code is already optimised )
https://github.com/pygame-web/pygbag/assets/90169211/8bafb22a-1d86-4fe5-88ca-b3442ba46fc2

**Comment by pmp-p** [comment]
first you cannot get HIGH framerate, it is fixed by platform/device/vendor and is usually 60 image per second since most screen still use 60 Hertz vertical refresh.

But if you get LOW framerate, either try to optimize your code and especially animation to sync to at least 30 ips to get less visual artefact. If python code cannot get faster the easy solution is to reduce surface of sprites and screen ( eg 4x speedup for half the size in with/height ), the harder solution is to use cython or mypy compiled code.

Typically 1024x600 is a sane screen surface for mobile.

**Comment by tigercoding56** [comment]
> first you cannot get HIGH framerate, it is fixed by platform/device/vendor and is usually 60 image per second since most screen still use 60 Hertz vertical refresh.
> 
> But if you get LOW framerate, either try to optimize your code and especially animation to sync to at least 30 ips to get less visual artefact. If python code cannot get faster the easy solution is to reduce surface of sprites and screen ( eg 4x speedup for half the size in with/height ), the harder solution is to use cython or mypy compiled code.
> 
> Typically 1024x600 is a sane screen surface for mobile.

well , 840-640x      and 2 fps , (on desktop i get about 140fps  , so 30fps was my expectation ) , after further investigation (since according to the comment pygbag should be able to handle it) , i found  that loading resources is expensive , which not only includes pygame.image.load as i assumed but also  , pygame.font.Font() , pygame.mixer.Sound() , and pygame.mixer.music.load()
