### ISSUE TITLE
pygame.error: Surface doesn't have a colorkey

### ISSUE THREAD

**Issue by ragej4x** [pygame-web/pygbag#153]
pygame mixer init frequency=44100, size=-16, channels=2, buffer=2048
Task exception was never retrieved
future: <Task finished name='main_loop' coro=<main_loop() done, defined at <console>:9> exception=error("Surface doesn't have a colorkey")>
Traceback (most recent call last):
  File "<console>", line 360, in main_loop
  File "<console>", line 109, in __init__
pygame.error: Surface doesn't have a colorkey

**Comment by pmp-p** [comment]
Please share complete project if you cannot explain what you are trying to do, because this is not a proper bug report.

i can only guess you forgot numpy at top of main.py and the PEP block

# /// script
# dependencies = [
#    "numpy",
#    "pygame-ce",
# ]
# ///

import numpy
import asyncio
import pygame
```

**Comment by ragej4x** [comment]
its on pygame

**Comment by pmp-p** [comment]
missing info
